import Prefecture from "~/types/prefecture";
import Spot from "~/types/spot";

export const PREFECTURE_SPOTS: Record<Prefecture, Array<Spot>> = {
  [Prefecture.JP_01]: [],
  [Prefecture.JP_02]: [],
  [Prefecture.JP_03]: [],
  [Prefecture.JP_04]: [],
  [Prefecture.JP_05]: [],
  [Prefecture.JP_06]: [],
  [Prefecture.JP_07]: [],
  [Prefecture.JP_08]: [],
  [Prefecture.JP_09]: [],
  [Prefecture.JP_10]: [],
  [Prefecture.JP_11]: [],
  [Prefecture.JP_12]: [],
  [Prefecture.JP_13]: [],
  [Prefecture.JP_14]: [],
  [Prefecture.JP_15]: [],
  [Prefecture.JP_16]: [],
  [Prefecture.JP_17]: [],
  [Prefecture.JP_18]: [],
  [Prefecture.JP_19]: [],
  [Prefecture.JP_20]: [],
  [Prefecture.JP_21]: [],
  [Prefecture.JP_22]: [],
  [Prefecture.JP_23]: [],
  [Prefecture.JP_24]: [],
  [Prefecture.JP_25]: [],
  [Prefecture.JP_26]: [],
  [Prefecture.JP_27]: [],
  [Prefecture.JP_28]: [],
  [Prefecture.JP_29]: [],
  [Prefecture.JP_30]: [],
  [Prefecture.JP_31]: [],
  [Prefecture.JP_32]: [],
  [Prefecture.JP_33]: [],
  [Prefecture.JP_34]: [],
  [Prefecture.JP_35]: [],
  [Prefecture.JP_36]: [],
  [Prefecture.JP_37]: [],
  [Prefecture.JP_38]: [],
  [Prefecture.JP_39]: [],
  [Prefecture.JP_40]: [],
  [Prefecture.JP_41]: [],
  [Prefecture.JP_42]: [],
  [Prefecture.JP_43]: [],
  [Prefecture.JP_44]: [],
  [Prefecture.JP_45]: [],
  [Prefecture.JP_46]: [],
};
