import Spot from "~/types/spot";

export function getSpotChineseName(type: Spot) {
    switch(type) {
        case Spot.NAGOYA_CASTLE:
            return "名古屋城";
        case Spot.OSAKA_CASTLE:
            return "大阪城";
        case Spot.KUMAMOTO_CASTLE:
            return "熊本城";
        case Spot.HAKODATE_NIGHT:
            return "函館山夜景";
        case Spot.MAYA_NIGHT:
            return "摩耶山夜景";
        case Spot.INASA_NIGHT:
            return "稻佐山夜景";
        case Spot.KENROKU_EN:
            return "兼六園";
        case Spot.KORAKU_EN:
            return "後樂園";
        case Spot.KAIRAKU_EN:
            return "偕樂園";
        case Spot.MATSUSHIMA_VIEW:
            return "松島";
        case Spot.AMANOHASHIDATE_VIEW:
            return "天橋立";
        case Spot.ITSUKUSHIMA_VIEW:
            return "宮島";
        case Spot.SHIRAKAWA_VILLAGE:
            return "白川鄉";
        case Spot.MIYAMA_VILLAGE:
            return "美山町";
        case Spot.OUCHIJUKU_VILLAGE:
            return "大內宿";
        case Spot.GERO_SPRING:
            return "下呂溫泉";
        case Spot.ARIMA_SPRING:
            return "有馬溫泉";
        case Spot.KUSATSU_SPRING:
            return "草津溫泉";
        case Spot.ISE_JINGU:
            return "伊勢神宮";
        case Spot.MEIJI_JINGU:
            return "明治神宮";
        case Spot.HEIAN_JINGU:
            return "平安神宮";
        case Spot.ATSUTA_JINGU:
            return "熱田神宮";
        case Spot.KANDA_MATSURI:
            return "神田祭";
        case Spot.GION_MATSURI:
            return "祇園祭";
        case Spot.TENJIN_MATSURI:
            return "天神祭";
        case Spot.NAGAO_HANABI:
            return "長岡花火大會";
        case Spot.OOMAGARI_HANABI:
            return "大曲花火大會";
        case Spot.TSUCHIURA_HANABI:
            return "土浦花火大會";
        case Spot.KITANO_TEN:
            return "北野天滿宮";
        case Spot.DAIZAIFU_TEN:
            return "太宰府天滿宮";
        case Spot.WAKAURA_TEN:
            return "和歌浦天満宮";
        case Spot.YOKOHAMA_CH:
            return "橫濱中華街";
        case Spot.NANKIN_CH:
            return "南京町中華街";
        case Spot.SHINCHI_CH:
            return "新地町中華街";
        case Spot.YOSHIHARA_FU:
            return "吉原風俗街";
        case Spot.NAKASU_FU:
            return "中洲風俗街";
        case Spot.SUSUKINO_FU:
            return "薄野風俗街";
        case Spot.UJI_TEA:
            return "宇治茶";
        case Spot.SHIZUOKA_TEA:
            return "靜岡茶";
        case Spot.SAYAMA_TEA:
            return "狹山茶";
        case Spot.MATSUSAKA_COW:
            return "松阪牛";
        case Spot.KOBE_COW:
            return "神戶牛";
        case Spot.OUMI_COW:
            return "近江牛";
        case Spot.HAKATA_RAMEN:
            return "博多拉麵";
        case Spot.SAPPORO_RAMEN:
            return "札幌拉麵";
        case Spot.KITAKATA_RAMEN:
            return "喜多方拉麵";
        default:
            return "";
    }
}